name: Android CD with Slack Integration

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Upload to Slack
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # 3. Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      # 4. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 5. Accept licenses
      - name: Accept licenses
        run: yes | sdkmanager --licenses || true

      # 6. Build release APK
      - name: Build APK
        run: ./gradlew assembleDebug


      # 8. Upload APK to Slack
      - name: Upload APK to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          UPLOAD_RESPONSE=$(curl -s -X POST \
          -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
          -F "channels=#deploy" \
          -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
          -F "filename=app-release.apk" \
          -F "initial_comment=New APK build available for ${{ github.ref_name }}" \
          https://slack.com/api/files.upload)
          
          echo "Response from Slack: $UPLOAD_RESPONSE"