name: Android CD with Slack Integration

on:
  push:
    tags:
      - 'v*' # Trigger on version tags (e.g., v1.0.0)

jobs:
  build:
    name: Build and Upload to Slack
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # 3. Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      # 4. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 5. Accept licenses
      - name: Accept licenses
        run: yes | sdkmanager --licenses || true

      # 6. Build release APK
      - name: Build APK
        run: ./gradlew :app:assembleRelease

      # 7. Upload APK to Slack
      - name: Upload APK to Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          curl -F channels=#deploy \
               -F file=@app/build/outputs/apk/release/app-release.apk \
               -F initial_comment="New APK build is available for version ${{ github.ref_name }}" \
               -F title="app-release.apk" \
               -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
               https://slack.com/api/files.upload